// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/random.proto

package randompb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RandomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RandomRequest) Reset() {
	*x = RandomRequest{}
	mi := &file_proto_random_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RandomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomRequest) ProtoMessage() {}

func (x *RandomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_random_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomRequest.ProtoReflect.Descriptor instead.
func (*RandomRequest) Descriptor() ([]byte, []int) {
	return file_proto_random_proto_rawDescGZIP(), []int{0}
}

type RandomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          string                 `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RandomResponse) Reset() {
	*x = RandomResponse{}
	mi := &file_proto_random_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RandomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomResponse) ProtoMessage() {}

func (x *RandomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_random_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomResponse.ProtoReflect.Descriptor instead.
func (*RandomResponse) Descriptor() ([]byte, []int) {
	return file_proto_random_proto_rawDescGZIP(), []int{1}
}

func (x *RandomResponse) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

var File_proto_random_proto protoreflect.FileDescriptor

const file_proto_random_proto_rawDesc = "" +
	"\n" +
	"\x12proto/random.proto\x12\x06random\"\x0f\n" +
	"\rRandomRequest\"$\n" +
	"\x0eRandomResponse\x12\x12\n" +
	"\x04word\x18\x01 \x01(\tR\x04word2S\n" +
	"\rRandomService\x12B\n" +
	"\x0fGetRandomStream\x12\x15.random.RandomRequest\x1a\x16.random.RandomResponse0\x01B\x19Z\x17proto/randompb;randompbb\x06proto3"

var (
	file_proto_random_proto_rawDescOnce sync.Once
	file_proto_random_proto_rawDescData []byte
)

func file_proto_random_proto_rawDescGZIP() []byte {
	file_proto_random_proto_rawDescOnce.Do(func() {
		file_proto_random_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_random_proto_rawDesc), len(file_proto_random_proto_rawDesc)))
	})
	return file_proto_random_proto_rawDescData
}

var file_proto_random_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_random_proto_goTypes = []any{
	(*RandomRequest)(nil),  // 0: random.RandomRequest
	(*RandomResponse)(nil), // 1: random.RandomResponse
}
var file_proto_random_proto_depIdxs = []int32{
	0, // 0: random.RandomService.GetRandomStream:input_type -> random.RandomRequest
	1, // 1: random.RandomService.GetRandomStream:output_type -> random.RandomResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_random_proto_init() }
func file_proto_random_proto_init() {
	if File_proto_random_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_random_proto_rawDesc), len(file_proto_random_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_random_proto_goTypes,
		DependencyIndexes: file_proto_random_proto_depIdxs,
		MessageInfos:      file_proto_random_proto_msgTypes,
	}.Build()
	File_proto_random_proto = out.File
	file_proto_random_proto_goTypes = nil
	file_proto_random_proto_depIdxs = nil
}
