version: "3.9"

services:
  service-a:
    build:
      context: .
      dockerfile: service-a/Dockerfile
    container_name: service-a
    ports:
      - "50051:50051"   # expõe a porta padrão gRPC

  service-b:
    build:
      context: .
      dockerfile: service-b/Dockerfile
    container_name: service-b
    depends_on:
      - service-a
    environment:
      - SERVICE_A_ADDR=service-a:50051
